name: CI

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"
    branches:
      - main
  schedule:
    - cron: 0 0 * * 5

jobs:
  plugin_test:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        source-build:
          - null
          - true

    runs-on: ${{ matrix.os }}

    name: asdf-raku on ${{ matrix.os }} (ASDF_RAKU_BUILD=${{ matrix.source-build }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install system packages on Ubuntu
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get install curl

      - name: Install system packages on macOS
        if: ${{ runner.os == 'macOS' }}
        run: brew install coreutils

      - name: Test plugin
        uses: asdf-vm/actions/plugin-test@v1
        env:
          ASDF_RAKU_BUILD: ${{ matrix.source-build }}
        with:
          command: raku --version
